function [transmural, apicobasal, transmural_fibers, interventricular]=computeUVC(VoxelMat,tag,res)
% computeUVC generates transmural and apicobasal coordinates into a
% voxelized geometry with labelled surfaces.
%
% [transmural, apicobasal]=computeUVC(VoxelMat,tag) generates the two
% coordinates by using the default resolution (res=0.25 mm). tag should be
% in the form as generated by the tagSurface function (i.e., an array of
% size numel(VoxelMat) with values different from 0 only in the voxels on
% the surface of the voxelized geometry.
%
% [transmural, apicobasal]=computeUVC(VoxelMat,tag,res) allows to define a
% different resolution.
%
% [transmural, apicobasal, transmural_fibers, interventricular]=computeUVC(VoxelMat,tag,res)
% should be call for biventricular meshes.
% In this case, computeUVC also outputs an additional scalar field
% (transmural_fibers) and the interventricular coordinate.
% transmural_fibers is a scalar field with value equal to 0 on the left
% ventricular endocardium, 0.5 on the right ventricular endocardium, and 1
% on the epicardium. Thus, its gradient results in a trasmural direction on
% the septum going from left to right ventricle.

if nargin<3
    res=0.25;
end

[FV,extInd]=computeSurface(VoxelMat,res);

%% transmural coordinate
seed=find(tag==2 | tag==3);

eik_endo=solveEikonal(VoxelMat,seed);

seed=find(tag==4);
eik_epi=solveEikonal(VoxelMat,seed);

transmural=eik_endo./(eik_epi+eik_endo);
%% apicobasal
disp('Select apex point')
plot_selected=selectSurface(VoxelMat,FV,extInd,res,1,1);

seed=find(plot_selected);
eik_apex=solveEikonal(VoxelMat,seed);
seed=find(tag==1 & not(plot_selected(:)));
eik_base=solveEikonal(VoxelMat,seed);
apicobasal=eik_apex./(eik_base+eik_apex);

if nargout>2
    seed=find(tag==2);
    eik_rv=solveEikonal(VoxelMat,seed);

    seed=find(tag==3 | tag==4);
    eik_lv_epi=solveEikonal(VoxelMat,seed);

    seed=find(tag==3);
    eik_lv=solveEikonal(VoxelMat,seed);

    seed=find(tag==2 | tag==4);
    eik_rv_epi=solveEikonal(VoxelMat,seed);
    
    phi_lv=eik_lv./(eik_lv+eik_rv_epi);
    phi_rv=eik_rv./(eik_rv+eik_lv_epi);
    transmural_fibers=(2*phi_lv+phi_rv-1)/2;

    interventricular=eik_lv./(eik_lv+eik_rv);
end


