function plotPurkinje(VoxelMat,transmural,nodes,elem,act_times)
% plotPurkinje plot a Purkinje tree as generated by the createPurkinje
% function on the the voxelized geometry VoxelMat.
% The plotPurkinje function also requires a matrix of the same size of
% VoxelMat or a vector of size numel(VoxelMat) with values equal to 0 in
% the inidices corresponding to surface endocardial voxels.
% The transmural coordinate as computed by the computeUVC function can be
% used as such an input.

endo=zeros(size(VoxelMat));
endo(transmural==0)=1;

[FV1,extInd1]=computeSurface(endo,1);

root=nodes(act_times==0,:);

figure;
PlotVoxel(FV1,endo,extInd1,[100 100 100]/255,0.1,1);
hold on
for i=1:size(elem,1)
patch(nodes(elem(i,:),1),nodes(elem(i,:),2),nodes(elem(i,:),3),...
    act_times(elem(i,:)),'EdgeColor','interp','LineWidth',3);
end
colorbar;
colormap('jet');
scatter3(root(1),root(2),root(3),50,'blue','filled','o');